repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: [ --fix ]
        files: '^(packages/nameguard-python|apps/api.namerank.io)/.*\.py'
      - id: ruff-format
        files: '^(packages/nameguard-python|apps/api.namerank.io)/.*\.py'
