import React from "react";
import { API_VERSION } from "@namehash/nameguard";

export const ReportFooter = () => {
  return (
    <div className="text-center px-6">
      <p className="text-sm leading-6 text-gray-500">
        Report generated by NameGuard ({API_VERSION})
      </p>
    </div>
  );
};
