import React from "react";

export const ReportFooter = () => {
  return (
    <div className="ng-text-center ng-px-6">
      <p className="ng-text-sm ng-leading-6 ng-text-gray-500">
        Report generated by NameGuard (v0.8-beta)
      </p>
    </div>
  );
};
