import React from "react";

export const ReportFooter = () => {
  return (
    <div className="text-center px-6">
      <p className="text-sm leading-6 text-gray-500">
        Report generated by NameGuard (v0.8-beta)
      </p>
    </div>
  );
};
