import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Head from "next/head";
import { Header } from "@/components/organisms/header";
import { NamekitFooter } from "@/components/organisms/namekit-footer";

const unifont = localFont({
  src: "./fonts/unifont.otf",
  variable: "--font-unifont",
});

const adobeBlank = localFont({
  src: "./fonts/AdobeBlank.ttf",
  variable: "--font-adobe-blank",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        {/* Fonts */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
      </Head>
      <body
        className={`${unifont.variable} ${adobeBlank.variable} antialiased`}
      >
        <Header />
        {children}
        <NamekitFooter />
      </body>
    </html>
  );
}
