import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Search } from "@/components/Search";

const inter = Inter({ variable: "--font-inter", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NameGuard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <Search />
        {children}
      </body>
    </html>
  );
}
