name: ens-utils

on:
  push:
    branches:
      - main
    paths:
      - "packages/ens-utils/**"
  pull_request:
    branches:
      - main
    # paths:
    #   - "packages/ens-utils/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install Dependencies
        run: pnpm install
      - name: Build ens-utils
        run: pnpm --filter ./packages/ens-utils build
      - name: Test ens-utils
        run: pnpm --filter ./packages/ens-utils test
