name: NameGuard API - PyPI Package Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout NameKit repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pip dependencies
        working-directory: ./packages/nameguard-python
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build NameGuard package
        working-directory: ./packages/nameguard-python
        run: python -m build

      - name: Publish NameGuard package
        uses: pypa/gh-action-pypi-publish@release/v1.8
        with:
          packages-dir: packages/nameguard-python/dist/
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
