name: nameguard-js

on:
  push:
    branches:
      - main
    paths:
      - "packages/nameguard-js/**"
  pull_request:
    branches:
      - main
    # paths:
    #   - "packages/nameguard-js/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install Dependencies
        run: pnpm install
      - name: Build nameguard-js
        run: pnpm --filter ./packages/nameguard-js build
      - name: Test nameguard-js
        run: pnpm --filter ./packages/nameguard-js test
